In [1]:
!pip install datasets

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: datasets in /home/sree/.local/lib/python3.10/site-packages (2.19.1)
Requirement already satisfied: pyarrow>=12.0.0 in /home/sree/.local/lib/python3.10/site-packages (from datasets) (16.0.0)
Requirement already satisfied: pyyaml>=5.1 in /usr/lib/python3/dist-packages (from datasets) (5.4.1)
Requirement already satisfied: filelock in /home/sree/.local/lib/python3.10/site-packages (from datasets) (3.14.0)
Requirement already satisfied: fsspec[http]<=2024.3.1,>=2023.1.0 in /home/sree/.local/lib/python3.10/site-packages (from datasets) (2024.3.1)
Requirement already satisfied: pyarrow-hotfix in /home/sree/.local/lib/python3.10/site-packages (from datasets) (0.6)
Requirement already satisfied: huggingface-hub>=0.21.2 in /home/sree/.local/lib/python3.10/site-packages (from datasets) (0.23.0)
Requirement already satisfied: numpy>=1.17 in /home/sree/.local/lib/python3.10/site-packages (from datasets) (1.26.4)
Requirement already satisfied: pandas in /home/sree/.local/lib/python3.10/site-packages (from datasets) (2.2.2)
Requirement already satisfied: xxhash in /home/sree/.local/lib/python3.10/site-packages (from datasets) (3.4.1)
Requirement already satisfied: tqdm>=4.62.1 in /home/sree/.local/lib/python3.10/site-packages (from datasets) (4.66.4)
Requirement already satisfied: multiprocess in /home/sree/.local/lib/python3.10/site-packages (from datasets) (0.70.16)
Requirement already satisfied: requests>=2.19.0 in /home/sree/.local/lib/python3.10/site-packages (from datasets) (2.31.0)
Requirement already satisfied: aiohttp in /home/sree/.local/lib/python3.10/site-packages (from datasets) (3.9.5)
Requirement already satisfied: packaging in /home/sree/.local/lib/python3.10/site-packages (from datasets) (24.0)
Requirement already satisfied: dill<0.3.9,>=0.3.0 in /home/sree/.local/lib/python3.10/site-packages (from datasets) (0.3.8)
Requirement already satisfied: async-timeout<5.0,>=4.0 in /home/sree/.local/lib/python3.10/site-packages (from aiohttp->datasets) (4.0.3)
Requirement already satisfied: attrs>=17.3.0 in /home/sree/.local/lib/python3.10/site-packages (from aiohttp->datasets) (23.2.0)
Requirement already satisfied: frozenlist>=1.1.1 in /home/sree/.local/lib/python3.10/site-packages (from aiohttp->datasets) (1.4.1)
Requirement already satisfied: aiosignal>=1.1.2 in /home/sree/.local/lib/python3.10/site-packages (from aiohttp->datasets) (1.3.1)
Requirement already satisfied: multidict<7.0,>=4.5 in /home/sree/.local/lib/python3.10/site-packages (from aiohttp->datasets) (6.0.5)
Requirement already satisfied: yarl<2.0,>=1.0 in /home/sree/.local/lib/python3.10/site-packages (from aiohttp->datasets) (1.9.4)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /home/sree/.local/lib/python3.10/site-packages (from huggingface-hub>=0.21.2->datasets) (4.11.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /home/sree/.local/lib/python3.10/site-packages (from requests>=2.19.0->datasets) (3.3.2)
Requirement already satisfied: certifi>=2017.4.17 in /usr/lib/python3/dist-packages (from requests>=2.19.0->datasets) (2020.6.20)
Requirement already satisfied: idna<4,>=2.5 in /usr/lib/python3/dist-packages (from requests>=2.19.0->datasets) (3.3)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/lib/python3/dist-packages (from requests>=2.19.0->datasets) (1.26.5)
Requirement already satisfied: tzdata>=2022.7 in /home/sree/.local/lib/python3.10/site-packages (from pandas->datasets) (2024.1)
Requirement already satisfied: python-dateutil>=2.8.2 in /home/sree/.local/lib/python3.10/site-packages (from pandas->datasets) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/lib/python3/dist-packages (from pandas->datasets) (2022.1)
Requirement already satisfied: six>=1.5 in /usr/lib/python3/dist-packages (from python-dateutil>=2.8.2->pandas->datasets) (1.16.0)

In [ ]:
from datasets import load_dataset
dataset1 = load_dataset("McAuley-Lab/Amazon-Reviews-2023", "raw_review_Movies_and_TV", trust_remote_code=True)
dataset2 = load_dataset("McAuley-Lab/Amazon-Reviews-2023", "raw_review_Books", trust_remote_code=True)
dataset3 = load_dataset("McAuley-Lab/Amazon-Reviews-2023", "raw_review_CDs_and_Vinyl", trust_remote_code=True)
dataset4 = load_dataset("McAuley-Lab/Amazon-Reviews-2023", "raw_review_Cell_Phones_and_Accessories", trust_remote_code=True)
dataset5 = load_dataset("McAuley-Lab/Amazon-Reviews-2023", "raw_review_Electronics", trust_remote_code=True)
dataset6 = load_dataset("McAuley-Lab/Amazon-Reviews-2023", "raw_review_Clothing_Shoes_and_Jewelry", trust_remote_code=True)
dataset7= load_dataset("McAuley-Lab/Amazon-Reviews-2023", "raw_review_Digital_Music", trust_remote_code=True)

/home/sree/.local/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [ ]:
import pandas as pd
df1=pd.DataFrame(dataset1["full"][0:100000])
df2=pd.DataFrame(dataset2["full"][0:100000])
df3=pd.DataFrame(dataset3["full"][0:100000])
df4=pd.DataFrame(dataset4["full"][0:100000])
df5=pd.DataFrame(dataset5["full"][0:100000])
df6=pd.DataFrame(dataset6["full"][0:100000])
df7=pd.DataFrame(dataset7["full"][0:100000])

In [4]:
df2.to_csv("s2",index=False)

In [3]:
df1.to_csv("s1",index=False)
df3.to_csv("s3",index=False)
df4.to_csv("s4",index=False)
df5.to_csv("s5",index=False)
df6.to_csv("s6",index=False)
df7.to_csv("s7",index=False)

In [1]:
import pandas as pd
df1=pd.read_csv("s1")
df2=pd.read_csv("s2")
df3=pd.read_csv("s3")
df4=pd.read_csv("s4")
df5=pd.read_csv("s5")
df6=pd.read_csv("s6")
df7=pd.read_csv("s7")

In [2]:
df7.shape

(100000, 10)

In [6]:
common_user_ids=set(df1['user_id']).intersection(df2['user_id'])
df2_filtered=df2[df2["user_id"].isin(common_user_ids)]
df2_filtered.to_csv("s21",index=False)

In [ ]:
# Step 1: Find common user IDs
common_user_ids = set(df1['user_id']).intersection(df6['user_id'], df3['user_id'],df4['user_id'], df5['user_id'],df7['user_id'])

# Step 2: Filter dataframes using common user IDs
df1_filtered = df1[df1['user_id'].isin(common_user_ids)]
df7_filtered = df7[df7['user_id'].isin(common_user_ids)]
df3_filtered = df3[df3['user_id'].isin(common_user_ids)]
df4_filtered = df4[df4['user_id'].isin(common_user_ids)]
df5_filtered = df5[df5['user_id'].isin(common_user_ids)]
df6_filtered = df6[df6['user_id'].isin(common_user_ids)]

# Merging dataframes on 'user_id'
merged_df = pd.merge(df1_filtered, df3_filtered, on='user_id', how='outer')
merged_df = pd.merge(merged_df, df4_filtered, on='user_id', how='outer')
merged_df = pd.merge(merged_df, df5_filtered, on='user_id', how='outer')
merged_df = pd.merge(merged_df, df6_filtered, on='user_id', how='outer')
merged_df = pd.merge(merged_df, df7_filtered, on='user_id', how='outer')

In [3]:
df1_filtered.to_csv("s11",index=False)
df3_filtered.to_csv("s31",index=False)
df4_filtered.to_csv("s41",index=False)
df5_filtered.to_csv("s51",index=False)
df6_filtered.to_csv("s61",index=False)
df7_filtered.to_csv("s71",index=False)

In [ ]:
from datasets import load_dataset

dataset1M = load_dataset("McAuley-Lab/Amazon-Reviews-2023", "raw_meta_Movies_and_TV",split="full", trust_remote_code=True)
dataset2M = load_dataset("McAuley-Lab/Amazon-Reviews-2023", "raw_meta_Books",split="full", trust_remote_code=True)
dataset3M = load_dataset("McAuley-Lab/Amazon-Reviews-2023", "raw_meta_CDs_and_Vinyl",split="full", trust_remote_code=True)
dataset4M = load_dataset("McAuley-Lab/Amazon-Reviews-2023", "raw_meta_Cell_Phones_and_Accessories",split="full", trust_remote_code=True)
dataset5M = load_dataset("McAuley-Lab/Amazon-Reviews-2023", "raw_meta_Electronics",split="full", trust_remote_code=True)
dataset6M = load_dataset("McAuley-Lab/Amazon-Reviews-2023", "raw_meta_Clothing_Shoes_and_Jewelry",split="full", trust_remote_code=True)
dataset7M= load_dataset("McAuley-Lab/Amazon-Reviews-2023", "raw_meta_Digital_Music",split="full", trust_remote_code=True)
#print (dataset1M[0])

In [ ]:
import pandas as pd
df=pd.DataFrame(data2)

In [16]:
import pandas as pd
#data2=dataset2["full"][0:100000]
#data1=dataset1["full"][0:100000]
df1=pd.DataFrame(data1)
df2=pd.DataFrame(data2)

In [70]:
df1=df7

In [35]:
df1['title'].value_counts()

title
Five Stars                                    5340
Four Stars                                     988
Great                                          670
Great product                                  603
One Star                                       564
                                              ...
Good protector for your screen                   1
Sturdy case that is very pretty with bling       1
Broke so fast                                    1
Easy install and great clarity                   1
Too big for my iPhone 11.                        1
Name: count, Length: 62573, dtype: int64

In [ ]:
df2['title'].value_counts()

In [ ]:
df2.head()

In [ ]:
!pip install datetime

In [71]:
df1['timestamp'] = pd.to_datetime(df1['timestamp'], unit='ms')
sorted_df1 = df1.sort_values(by='timestamp')
#df2['timestamp'] = pd.to_datetime(df2['timestamp'], unit='ms')
#sorted_df2 = df2.sort_values(by='timestamp')

In [ ]:
sorted_df1.head()

In [ ]:
sorted_df2.head()

In [72]:
import pandas as pd

# Assuming df1 and df2 are your two DataFrames
# Merge the DataFrames on the 'user_id' column
#merged_df = pd.merge(sorted_df1, sorted_df2, on='user_id', how='inner')
merged_df = pd.merge(sorted_df1, df2, on='user_id', how='inner')
# Extract the overlapping user IDs
overlapping_users = merged_df['user_id'].unique()

print("Overlapping users:", len(overlapping_users))

Overlapping users: 125

In [ ]:
merged_df.head()

In [73]:
filtered_df1 = sorted_df1[sorted_df1['user_id'].isin(overlapping_users)]

In [39]:
#filtered_df2 = sorted_df2[sorted_df2['user_id'].isin(overlapping_users)]
filtered_df2 = df2[df2['user_id'].isin(overlapping_users)]

In [74]:
filtered_df1.to_csv("filtered_music", index=False)

In [64]:
filtered_df2.to_csv("filtered_books", index=False)

In [ ]:
filtered_df1.head()

In [ ]:
x=sorted_df1[sorted_df1['user_id']=='AFERCDY2EFJKT7QUQ75GISNHTFOQ']
x.head()

In [ ]:
filtered_df2.head()

In [ ]:
filtered_df1.shape

In [ ]:
filtered_df2.shape

LOAD META DATA

In [ ]:
dataset = load_dataset("McAuley-Lab/Amazon-Reviews-2023", "raw_meta_All_Beauty", split="full", trust_remote_code=True)

In [ ]:
from datasets import load_dataset

dataset3 = load_dataset("McAuley-Lab/Amazon-Reviews-2023", "raw_meta_Movies_and_TV",split="full", trust_remote_code=True)
#data3=dataset3["full"][0:2000]

In [ ]:
dataset3[:10]

In [ ]:
from datasets import load_dataset

dataset4 = load_dataset("McAuley-Lab/Amazon-Reviews-2023", "raw_meta_Books", split="full", trust_remote_code=True)
#data4=dataset4["full"][0:2000]

In [ ]:
import pandas as pd
df3=pd.DataFrame(dataset3)

In [ ]:
dataset4[:10]

In [79]:
import pandas as pd
data1=pd.read_csv("filtered_phones")
data2=pd.read_csv("../filtered_books")

In [66]:
df3.head()

,rating,title,text,images,asin,parent_asin,user_id,timestamp,helpful_vote,verified_purchase
0,5.0,Five Stars,LOVE IT!,[],B002MW50JA,B002MW50JA,AGKASBHYZPGTEPO6LWZPVJWB2BVA,2016-01-13 02:06:17.000,0,True
1,5.0,Five Stars,LOVE!!,[],B008XNPN0S,B008XNPN0S,AGKASBHYZPGTEPO6LWZPVJWB2BVA,2016-01-13 02:06:04.000,0,True
2,3.0,Three Stars,Sad there is not the versions with the real/or...,[],B00IKM5N02,B00IKM5N02,AGKASBHYZPGTEPO6LWZPVJWB2BVA,2016-01-13 01:51:25.000,0,True
3,3.0,Disappointed,I have listen to The Broadway 1958 Flower Drum...,[],B00006JKCM,B00006JKCM,AEVWAM3YWN5URJVJIZZ6XPD2MKIA,2006-11-20 15:34:24.000,3,True
4,5.0,Wonderful melding,Simply great album. One of the best. Marvelous...,[],B00013YRQY,B00013YRQY,AFWHJ6O3PV4JC7PVOJH6CPULO2KQ,2020-02-19 05:29:59.946,0,False

In [4]:
data2.head()

,rating,title,text,images,asin,parent_asin,user_id,timestamp,helpful_vote,verified_purchase
0,4.0,FRUGAL SPENDING HABITS WILL RESULT IN WEALTH A...,THIS BOOK GIVES GOOD INSIGHT INTO THE LIFESTYL...,[],1563523302,1563523302,AFERCDY2EFJKT7QUQ75GISNHTFOQ,1997-09-10 19:22:25,0,False
1,4.0,WHY THE &quot;TRIAL OF THE CENTURY&quot; WAS LOST,CHRIS DARDEN TRIES TO EXPLAIN THE FACTORS THAT...,[],0060391839,0060391839,AFERCDY2EFJKT7QUQ75GISNHTFOQ,1997-09-10 22:45:57,0,False
2,5.0,An ex-prosecutor shows his extreme disgust,If there is anybody out there who thinks that ...,[],0787111317,0787111317,AFERCDY2EFJKT7QUQ75GISNHTFOQ,1997-09-10 23:28:23,193,False
3,5.0,Don't be a fool.......be a skeptic,This book should serve as an inspiration to us...,[],0345409469,0345409469,AFERCDY2EFJKT7QUQ75GISNHTFOQ,1997-09-11 22:53:51,4,False
4,4.0,Thought provoking issues for the 21st century,&quot;Billions and Billions&quot; is another l...,[],0679411607,0679411607,AFERCDY2EFJKT7QUQ75GISNHTFOQ,1997-12-14 22:05:13,2,False

In [ ]:
data2.head()

In [80]:
import pandas as pd

# Assuming you have two dataframes: movie_df and books_df

# Merge the two dataframes on the user ID
merged_df = pd.merge(data1, data2, on='user_id', suffixes=('_phones', '_book'))

# Filter the merged dataframe based on the condition: movie timestamp < book timestamp
filtered_df = merged_df[(merged_df['timestamp_phones'] < merged_df['timestamp_book'])]

# Add the book title column to the movie dataframe as the target
data1['Target_Title'] = filtered_df['title_book']

data1.dropna(subset=['Target_Title'], inplace=True)

# Count the occurrences of each user ID
user_counts = data1['user_id'].value_counts()

# Get the user IDs where the count is less than 2
users_to_remove = user_counts[user_counts < 2].index

# Filter the dataframe to remove rows with user IDs that occur less than 2 times
filtered_data = data1[~data1['user_id'].isin(users_to_remove)]

In [56]:
data1.head(10)

,rating,title,text,images,asin,parent_asin,user_id,timestamp,helpful_vote,verified_purchase,Target_Title
802,4.0,It's probably just me,Rating this printer as a 4 star for the follow...,[],B0032AN4N0,B0032AN4N0,AFSKPY37N3C43SOI5IEXEK5JSIYA,2010-07-22 10:42:14,1,False,Wit Wins and Works Wonders
803,5.0,Perfect for my phone,"My digital camera is quite large, so I actuall...",[],B002VPE1X4,B002VPE1X4,AECGR42H24LUU7DA7HEUMCRLTX7Q,2010-07-22 18:51:30,0,False,Discover Tennis Essentials
804,5.0,Job done,Well...not much to say really. Got it for my ...,[],B00006JN3G,B00006JN3G,AFPYCRUYSN6QZQ34BQVQHPBTWL6Q,2010-07-26 11:53:09,0,True,Discover Golf Essentials
805,3.0,Garmin 1390T - OK but not exceptional,I have another Garmin unit (275T) and have had...,[],B001U0O7RG,B001U0O7RG,AEZYFSO5CQGCRA7SWH3WUPTQ7WKQ,2010-07-31 23:04:56,3,True,Discover the Bible in Full-Color Illustrated D...
806,4.0,More Than Just a Television,The Tivax 3.5-Inch Digital TV is also a multim...,[],B003N18O88,B003N18O88,AFUSWNVA72MMWHGYWJ652SYX2JJQ,2010-08-01 07:14:05,6,False,Discovering the Bible Stories for the First Time
807,5.0,"Overall, a great little GPS",The good:<br /><br />Lane guidance. I like to...,[],B003FSTAGO,B004JXW1VK,AGLHRQLAWKWQKEF6VRO2Y3MRS4JQ,2010-08-02 17:56:16,0,False,Tap into the Power of Instinct
808,4.0,Very good TV with typical LCD shortcomings,"Got this, my first HDTV, for $749 total delive...",[],B0036WT3PW,B0036WT3PW,AER6WLSJPBPNOZIQWVHQBVOKTNCA,2010-08-04 18:01:10,33,False,Herbal Tea and Yoga
809,5.0,Universal Fishfinder Mount w/ 244 Flush Mount,Universal Fishfinder Mount w/ 244 Flush Mount-...,[],B0015NDGOI,B0015NDGOI,AE5VPKX64CVOPH6X75C7EQXAIGLA,2010-08-04 18:34:19,0,True,Causes and Consequence
810,4.0,Tom Tom grows on me every day,My first GPS was a hand me down Magellan that ...,[],B003BEDTBE,B003BEDTBE,AGCA64OUVM2TJGNN3IUXMEU7KF6Q,2010-08-09 20:52:38,2,False,The Voice of a Child
811,4.0,"No, it's not an iPad, it is much better.",I purchased my unit at [...] but I bought the ...,[],B0000ZPOUG,B0000ZPOUG,AGZYNKTWTUPP4ZLJ77LH7TFL6Y5A,2010-08-11 13:19:30,4,False,Lavishly Illustrated

In [81]:
import pandas as pd
from sklearn.model_selection import train_test_split

# Assuming you have loaded your datasets into pandas DataFrames: movie_df and books_df

# Sort datasets by timestamp
#data1.sort_values(by='timestamp', inplace=True)
#df2.sort_values(by='timestamp', inplace=True)

# Define the timestamp threshold for splitting (e.g., 80% for training)
timestamp_threshold = 0.8

# Function to split interactions for each user
def split_by_user(df):
    train_data = pd.DataFrame(columns=df.columns)
    test_data = pd.DataFrame(columns=df.columns)
    
    for user_id, user_data in df.groupby('user_id'):
        train, test = train_test_split(user_data, train_size=timestamp_threshold, shuffle=False)
        train_data = pd.concat([train_data, train])
        test_data = pd.concat([test_data, test])
    
    return train_data, test_data

# Split movie dataset
train, test = split_by_user(filtered_data)


# Optionally, you can reset the index if needed
#movie_train.reset_index(drop=True, inplace=True)
#movie_test.reset_index(drop=True, inplace=True)
#books_train.reset_index(drop=True, inplace=True)
#books_test.reset_index(drop=True, inplace=True)

# Now you have movie_train, movie_test, books_train, and books_test DataFrames
# containing training and testing data for movies and books datasets, respectively

/tmp/ipykernel_3450/2905739884.py:20: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  train_data = pd.concat([train_data, train])
/tmp/ipykernel_3450/2905739884.py:21: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  test_data = pd.concat([test_data, test])

In [45]:
!pip install scikit-learn

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: scikit-learn in /home/sree/.local/lib/python3.10/site-packages (1.4.2)
Requirement already satisfied: scipy>=1.6.0 in /home/sree/.local/lib/python3.10/site-packages (from scikit-learn) (1.13.0)
Requirement already satisfied: joblib>=1.2.0 in /home/sree/.local/lib/python3.10/site-packages (from scikit-learn) (1.4.2)
Requirement already satisfied: numpy>=1.19.5 in /home/sree/.local/lib/python3.10/site-packages (from scikit-learn) (1.26.4)
Requirement already satisfied: threadpoolctl>=2.0.0 in /home/sree/.local/lib/python3.10/site-packages (from scikit-learn) (3.5.0)

In [ ]:
train.head()

In [ ]:
test.head()

In [82]:
train.to_csv("trainphones_books",index=False)
test.to_csv("testelectronics_books",index=False)

df1.head()

#Concatenating all train data

In [88]:
import os
import pandas as pd

# Directory containing the CSV files
folder_path = "/home/sree/Desktop/Amazon Datasets/code"

# Get list of files in the directory
file_list = os.listdir(folder_path)

# Filter files starting with "train" and ending with ".csv"
train_files = [file for file in file_list if file.startswith("test")]

# Concatenate CSV files
dfs = []
for file in train_files:
    file_path = os.path.join(folder_path, file)
    df = pd.read_csv(file_path)
    dfs.append(df)

# Concatenate all DataFrames in the list
merged_df = pd.concat(dfs, ignore_index=True)

# Output the merged DataFrame
print(merged_df)

      rating                                       title  \
0        5.0                                  Five Stars
1        5.0                                       Great
2        5.0  Brilliant, epic 70s album FINALLY on CD!!!
3        5.0                                Fantastic CD
4        5.0                            BUY THIS AT ONCE
...      ...                                         ...
7765     4.0                       Good screen protector
7766     5.0                          Sleek base machine
7767     5.0                                  Work well.
7768     5.0                        Good To Have Around!
7769     5.0                               Phone Battery

                                                   text  \
0                                     Bear is a genius!
1                    Great! Great! Love some Buddy Guy!
2     You have GOT to hear this album, buy it AT ONC...
3     Unfortunately NOT available on any popular mus...
4     "You just can't find music like this any more"...
...                                                 ...
7765  This is high quality anti-glare screen protect...
7766  Very sleak looking speaker with great sound, s...
7767                I thought these were a great price.
7768  My hubbies goes through touch pens like water ...
7769  Husband was able to change his phone battery p...

                                                 images        asin  \
0                                                    []  B013JB2LXU
1                                                    []  B0000032DK
2     [{'attachment_type': 'IMAGE', 'large_image_url...  B001DJ7PD2
3                                                    []  B0012X4LL8
4                                                    []  B001PSFAF6
...                                                 ...         ...
7765                                                 []  B009A51Y1U
7766                                                 []  B09VYH3ZKM
7767                                                 []  B076NQM7GM
7768                                                 []  B01IHBVGOM
7769                                                 []  B08MDFCSZ3

     parent_asin                       user_id                timestamp  \
0     B013JB2LXU  AE22CFXT3QZKUQJORVTGL3VQXAAA  2015-12-22 00:05:06.000
1     B0000032DK  AE26V67R6SYRBNAVUGZ2ROE5BAFQ  2019-11-04 15:27:49.296
2     B001DJ7PD2  AE2ODZ4VYQ5FNNCONSHSNZM7PHSQ  2009-01-08 17:38:10.000
3     B0012X4LL8  AE2ODZ4VYQ5FNNCONSHSNZM7PHSQ  2010-10-18 13:38:51.000
4     B001PSFAF6  AE2ODZ4VYQ5FNNCONSHSNZM7PHSQ  2012-03-12 03:56:58.000
...          ...                           ...                      ...
7765  B009A51Y1U  AHZR5WMNDR6WQD5XZO36JFTUJ4NQ  2013-05-16 05:49:33.000
7766  B09QPPFCFD  AHZR5WMNDR6WQD5XZO36JFTUJ4NQ  2022-08-05 04:29:29.849
7767  B076NQM7GM  AHZWDQGQLQLCZRUF4YYYLESXSPZA  2020-09-09 02:57:28.392
7768  B09WVRFMCX  AHZZJQYNVZUJNPNQ737ITGEQUB4A  2021-05-03 15:47:20.703
7769  B08MDFCSZ3  AHZZJQYNVZUJNPNQ737ITGEQUB4A  2022-06-15 21:51:52.725

      helpful_vote  verified_purchase  \
0                0              False
1                0               True
2                5               True
3                3               True
4                3              False
...            ...                ...
7765             0              False
7766             1              False
7767             0               True
7768             0               True
7769             0               True

                                           Target_Title
0     Beautiful Honest Poems and Reflections From th...
1                  Change Your Recipes Change Your Life
2                                         Not for me...
3                Great writing; cheap facsimile edition
4     In Sookie's seventh adventure, it's like 24 me...
...                                                 ...
7765  Useful information here, but could have been b...
7766                                Stories for sharing
7767                             Starts with the basics
7768                                  Very suspenseful.
7769                              Laura's Natural World

[7770 rows x 11 columns]

In [86]:
merged_df.head()

,rating,title,text,images,asin,parent_asin,user_id,timestamp,helpful_vote,verified_purchase,Target_Title
0,5.0,Five Stars,Love it!,[],B018Y224PY,B010BWYDYA,AE223GHNZEI5MRMBVVRGJONDNWRQ,2016-09-06 00:15:24.000,0,True,"Very good episode guide, but a few issues"
1,5.0,Awesome!,"This was a Christmas gift from my daughter, I ...",[],B07HZLHPKP,B07HZLHPKP,AE223GHNZEI5MRMBVVRGJONDNWRQ,2020-02-15 04:48:15.581,0,True,1928 goes out in style
2,5.0,Television,What a great TV my daughter loves it!!,[],B092Q527H1,B0BHHVS86S,AE223GHNZEI5MRMBVVRGJONDNWRQ,2022-02-16 07:59:44.744,0,True,A Gentle and Deeply Meaningful Guide Through G...
3,5.0,This cover is great,The case is exactly as it shows!,[],B085PVJR93,B096SCTX39,AE223GHNZEI5MRMBVVRGJONDNWRQ,2022-08-02 05:14:43.808,0,True,A Big Cookbook With a Lot of Healthy Promise
4,2.0,Poor quality and broken right out of the packa...,Very Poor Quality - I ordered 2 and in 1 packa...,[],B00B1GVD5I,B00B1GVD5I,AE224GVO7OHTYF26U6ER6BEVIUAQ,2015-02-18 12:43:59,0,True,Howling at the Loon

In [89]:
merged_df.to_csv("multidomaintest",index=False)

#Preparation of data for training and testing using common userid among all the domains

In [ ]:
import pandas as pd
#df=pd.read_csv("s71")
df=pd.read_csv("s21")
df=df[["user_id","asin","rating","text","timestamp"]]
df['timestamp'] = pd.to_datetime(df['timestamp'], unit='ms')
df=df.rename(columns={"text":"product review","asin":"Product Id"})
df.head()

In [ ]:
df.shape

In [ ]:
dfM=pd.DataFrame(dataset2M[0:200000])
#dfM=pd.DataFrame(dataset1M[300000:1000000])
#df1M=dfM[["parent_asin","title"]]
df1M = dfM.rename(columns={'title': 'Product Title','parent_asin':'Product Id'})
df1M.head()

In [ ]:
merged_df = pd.merge(df, df1M, on='Product Id', how='left')

In [ ]:
merged_df.head()

In [ ]:
nan_counts = merged_df.isnull().sum()

In [ ]:
nan_counts

In [2]:
import pandas as pd
df=pd.read_csv("AllBooks_product")

In [3]:
df.head()

,user_id,Product Id,rating,product review,timestamp,main_category,Product Title,average_rating,rating_number,features,description,price,images,videos,store,categories,details,bought_together,subtitle,author
0,AFKZENTNBQ7A7V7UXW5JJI6UGRYQ,B09BGPFTDB,1.0,It is definitely not a watercolor book. The p...,2022-01-17 06:06:38.485,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,AFKZENTNBQ7A7V7UXW5JJI6UGRYQ,0593235657,5.0,Updated: after first book arrived very damaged...,2021-12-27 18:26:44.904,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,AFKZENTNBQ7A7V7UXW5JJI6UGRYQ,1782490671,5.0,I bought it for the bag on the front so it pai...,2021-12-24 22:04:55.102,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,AFKZENTNBQ7A7V7UXW5JJI6UGRYQ,0593138228,5.0,Updated: after 1st arrived damaged the replace...,2021-12-24 16:55:06.602,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,AFKZENTNBQ7A7V7UXW5JJI6UGRYQ,0823098079,5.0,I love this book! The patterns are lovely. I ...,2021-11-19 08:57:33.230,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
#merged_df=merged_df[merged_df["rating"]>3]

In [ ]:
merged_df.head()

In [ ]:
merged_df.to_csv("AllBooks_product",index=False)

In [ ]:
import pandas as pd

def load_and_process_dataset(file_path, columns_to_keep=None, rename_columns=None):
    """
    Load a dataset from a CSV file, select specific columns, and rename them.
    
    Parameters:
        file_path (str): Path to the CSV file.
        columns_to_keep (list): List of column names to keep. If None, keep all columns.
        rename_columns (dict): Dictionary mapping old column names to new ones for renaming.
        
    Returns:
        pandas.DataFrame: Processed DataFrame.
    """
    # Load the dataset
    df = pd.read_csv(file_path)
    
    # Select specific columns if specified
    if columns_to_keep:
        df = df[columns_to_keep]
    
    # Rename columns if specified
    if rename_columns:
        df.rename(columns=rename_columns, inplace=True)
    
    return df


def merge_dataframes(left_df, right_df, on_column, how='left'):
    """
    Merge two DataFrames on a specified column.
    
    Parameters:
        left_df (pandas.DataFrame): Left DataFrame.
        right_df (pandas.DataFrame): Right DataFrame.
        on_column (str): Name of the column to merge on.
        how (str): Type of merge to be performed ('left', 'right', 'outer', 'inner').
        
    Returns:
        pandas.DataFrame: Merged DataFrame.
    """
    merged_df = pd.merge(left_df, right_df, on=on_column, how=how)
    return merged_df


# Example usage:
List1=["s41","s51","s61","s71"]
List2=[dataset4M,dataset5M,dataset6M,dataset7M]
List3=["phones","electronics","clothing","digitalmusic"]
for i,j,k in zip(List1,List2,List3):
    # Load and process first dataset
    df = load_and_process_dataset(i, columns_to_keep=["user_id", "asin", "rating", "text", "timestamp"], rename_columns={"text": "product review", "asin": "Product Id"})

    # Load and process second dataset
    #dfM = load_and_process_dataset(j, rename_columns={"parent_asin": "Product Id", "title": "Product Title"})
    # Process the secondary dataset
    dfM = pd.DataFrame(j)
    dfM = dfM[["parent_asin", "title"]]
    dfM = dfM.rename(columns={'title': 'Product Title', 'parent_asin': 'Product Id'})
    # Merge the two dataframes
    merged_df = merge_dataframes(df, dfM, on_column="Product Id", how="left")

# Display the merged DataFrame
    print(merged_df.head())
    merged_df.to_csv("{k}_products",index=False)